appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: n8Kx+/nBSbWeaVwTrRMO/baOizyOkcn0aUtudXtJWUNrk3A+z5PUr1TXH/VuOgUpjQrW/QBxKggEmi8cs9KLKimSjbxsJJptBUA825XiQ1i2RGn2IMGtNxzWXlgoKciNuLvXzdklHU60DMQHnmgrZoWlX1KgD2eQOZr59D2V4CaLVqug5xW2XNJGtxMBRzbjG+5AzlfLcJc7cjWjPVpNpmZk1qCkyqU5vHmSW/7exRQ6LwpkztTT3BBDqice9uTCiU1gab5oK5zMexkCNN69fa9V7tWMiZtcIn1/GZjwX+p3CQZMmbEfxNThNe1bX1aVZEwdhdmz+dcjA2IA+9m1kieS83ateJ7RPY/JN7gDf0WAOuVU3Qw/GBnyw5SRgyk5wltCarDxdjCBYMcycaeO+jxOgZbr8K3vMYyZIdpzgUmk/noJe2/3vPH6oiKQ2b7uc4OmfdM/UHfhZBaHBirSRQ/s3yYfvoKD4oYiEG3J8pCyb0QXAW3D6wv/HlWOoCgvJ2BwBz/R0473J+oEaAatyxSFXyK7Abun54L7t4mjQhH+d/81iQXKB53dkRyNK+L3KoLONGgUv1dCUedbPdpaotL0plpFgdvQRuso//jjNqbrSF46HVhZGNkdHtRK6TaCrFvxz0lq2aBTrH2fYN645gylZ/pAEm3P7uR/npYkSwQ=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: false
